cd "c:/Users/Administrator/Desktop/yolok210/yolo-for-k210_320240/yolo-for-k210_320240/kendryte_kpu-standalone_3/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET APPDATA=C:\Users\Administrator\AppData\Roaming
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=WIN-8SVU6C5PINT
SET ComSpec=C:\Windows\system32\cmd.exe
SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
SET CUDA_PATH_V10_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
SET FP_NO_HOST_CHECK=NO
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\Administrator
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=C:\Users\Administrator\Desktop\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=C:\Users\Administrator\Desktop\KendryteIDE\\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=C:\Users\Administrator\Desktop\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\42153_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LOCALAPPDATA=C:\Users\Administrator\AppData\Local
SET LOGONSERVER=\\WIN-8SVU6C5PINT
SET MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit PDF Reader\plugins\
SET NUMBER_OF_PROCESSORS=12
SET NVCUDASAMPLES10_0_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0
SET NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0
SET NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
SET OS=Windows_NT
SET Path=c:\Users\Administrator\Desktop\KendryteIDE\bin;C:\Users\Administrator\Desktop\KendryteIDE\LocalPackage\toolchain\bin;C:\Users\Administrator\Desktop\KendryteIDE\LocalPackage\cmake\bin;C:\Users\Administrator\Desktop\KendryteIDE\LocalPackage\jlink;C:\Users\Administrator\Desktop\KendryteIDE\LocalPackage\clang-format\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
SET PROCESSOR_LEVEL=23
SET PROCESSOR_REVISION=7100
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PROMPT=$P$G
SET PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
SET PUBLIC=C:\Users\Public
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\Windows
SET SYSTEM_TEMP=C:\Users\ADMINI~1\AppData\Local\Temp
SET TEMP=C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=WIN-8SVU6C5PINT
SET USERNAME=Administrator
SET USERPROFILE=C:\Users\Administrator
SET VSCODE_CWD=C:\Users\Administrator\Desktop\KendryteIDE
SET VSCODE_IPC_HOOK=\\.\pipe\26638e7d8196f5ff0fc167830678d546-1.34.1-beta-main-sock
SET VSCODE_LOGS=C:\Users\Administrator\Desktop\KendryteIDE\UserData\latest\user-data\logs\20220119T212853
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"C:\\Users\\Administrator\\Desktop\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"C:\\Users\\Administrator\\Desktop\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"C:\\Users\\Administrator\\Desktop\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"C:\\Users\\Administrator\\Desktop\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=C:\Users\Administrator\Desktop\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=C:\Users\Administrator\Desktop\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=19720
SET VSCODE_PORTABLE=C:\Users\Administrator\Desktop\KendryteIDE\UserData\latest
SET windir=C:\Windows
SET windows_tracing_flags=3
SET windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log
SET PYTHONHOME=C:/Users/Administrator/Desktop/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=C:/Users/Administrator/Desktop/KendryteIDE/LocalPackage/python2library;C:/Users/Administrator/Desktop/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"C:/Users/Administrator/Desktop/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build c:/Users/Administrator/Desktop/yolok210/yolo-for-k210_320240/yolo-for-k210_320240/kendryte_kpu-standalone_3/build -- -j 11